environment: 'local'

app:
  bokeh:
    path: "$PATH"
  fastapi:
    path: "/"

proxy:
  bokeh:
    local:
      address: "127.0.0.1"
      port: "$PORT"
      path: "$PATH/ws"
  fastapi:
    local:
      address: "127.0.0.1"
      port: 8000
      path: "/"
    heroku:
      domain: "prtr-transfers-summary.herokuapp.com"
      address: "0.0.0.0"
      port: "$PORT"
      path: "/"
