version: '2'
services:
    bokeh_app:
        image: bokeh_app:prod 
        build:
            context: .
            dockerfile: Dockerfile.worker
        container_name: bokeh_app
        ports:
            - '5006:5006'
        volumes:
            - './:/PRTR_transfers_FastAPI'
    fastapi_app:
        image: fastapi_app:prod 
        depends_on:
            - bokeh_app
        build:
            context: .
            dockerfile: Dockerfile.web
        container_name: fastapi_app
        ports:
            - '8000:8000'
        volumes: 
            - './:/PRTR_transfers_FastAPI'
